### ISSUE TITLE
Error when run yarn build

### ISSUE THREAD

**Issue by TabrisEth** [pontem-network/aptos-wallet-adapter#3]
Pls help..
the branch is add-vue-provider, as i follow the docs, run npm build ,got error:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/102398699/193036911-e422d0e1-cd2b-48d0-95e3-521b3c5e1449.png">

**Comment by TabrisEth** [comment]
what 's your nodejs version? may i know this?

**Comment by lusd** [comment]
Hey @TabrisEth !
My node.js version is 16.14.2
Yeah we got that annoying message too. And managed to fix it, just pull latest updates. 

The reason that happens is because TypeScript is checking every folder which are imported in project directly, despite the fact we are telling to ignore those folders in tsconfig.json (field "exclude: [...]").
The source of error: imported TransactionPayload from "aptos/src/generated" and typescript decided to typecheck entire folder. And founded that annoying errors.
So, we imported required types for TransactionPayload more deeply from aptos and generated same type locally. And error has gone.
